from docx import Document
from docx.shared import Pt
from docx.oxml.ns import qn
import os

# Fungsi untuk mengisi template
def generate_cv(data, template_path, base_output_path):
    """
    Mengisi template dokumen dengan data dan menyimpannya di folder berdasarkan program studi.
    """
    # Buka template dokumen
    doc = Document(template_path)

    # Cari dan ganti placeholder di luar tabel
    for paragraph in doc.paragraphs:
        for key, value in data.items():
            # Mengganti {{Nama_Besar}} dengan format besar di bagian pertama
            if key == "Nama_Besar" and f"{{{{Nama_Besar}}}}" in paragraph.text:
                for run in paragraph.runs:
                    if f"{{{{Nama_Besar}}}}" in run.text:
                        run.font.size = Pt(18)
                        run.font.name = 'Arial'
                        run._element.rPr.rFonts.set(qn('w:eastAsia'), 'Arial')
                        run.text = run.text.replace(f"{{{{Nama_Besar}}}}", value)
            # Ganti placeholder lainnya termasuk {{Nama}} yang tidak diformat besar
            elif f"{{{{{key}}}}}" in paragraph.text:
                paragraph.text = paragraph.text.replace(f"{{{{{key}}}}}", value)

    # Cari dan ganti placeholder di dalam tabel
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for key, value in data.items():
                    if f"{{{{{key}}}}}" in cell.text:
                        cell.text = cell.text.replace(f"{{{{{key}}}}}", value)

    # Tentukan folder berdasarkan program studi
    program_studi = data.get("Program Studi", "Umum")
    output_folder = os.path.join(base_output_path, program_studi)
    
    # Buat folder jika belum ada
    os.makedirs(output_folder, exist_ok=True)
    
    # Tentukan path file output
    output_path = os.path.join(output_folder, f"Perjanjian_Kesediaan_{data['Nama'].replace(' ', '_').replace('.', '')}.docx")
    
    # Simpan dokumen yang sudah diisi
    doc.save(output_path)
    print(f"File berhasil disimpan di: {output_path}")

# Path template dan folder output utama
template_path = "Template_Perjanjian_Kesediaan.docx"
base_output_path = "output"

data_dosen_list = [
  {
    "Nama_Besar": "Satrio Tunggul Satoto Jagad",
    "Nama": "Satrio Tunggul Satoto Jagad",
    "Nama lengkap beserta gelar": "Satrio Tunggul Satoto Jagad, S.T., M.T.", 
    "NIP/NIK": "3471050612960002",
    "Tempat Lahir": "Yogyakarta",
    "Tanggal Lahir": "06 Desember 1996",
    "TTL": "Yogyakarta, 06 Desember 1996",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Kawin",
    "Agama": "Islam",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Jl Kranji, Serang Baru no.32, Mudal, Sariharjo, Ngaglik, Sleman, DI Yogyakarta",
    "Facs Rumah": "081289299534",
    "E-Mail": "satotojagad@gmail.com",
    "Tahun Lulus 1": "2020",
    "Perguruan Tinggi 1": "Universitas Gadjah Mada",
    "Prodi 1": "Departemen Teknik Sipil",
    "Tahun Lulus 2": "2022",
    "Perguruan Tinggi 2": "Universitas Gadjah Mada",
    "Prodi 2": "Magister Sistem dan Teknik Transformasi",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "Ahli Madya Teknik Jalan",
    "Jenis Pelatihan 1": "Dalam Negeri",
    "Penyelenggara Pelatihan 1": "Astekindo",
    "Jenis Sertifikat 1": "Sertifikat Keterangan Kerja Konstruksi",
    "Jangka Waktu Pelatihan 1": "3 Minggu",
    "Tahun Pelatihan 2": "Advanced Data Analytics",
    "Jenis Pelatihan 2": "Dalam Negeri",
    "Penyelenggara Pelatihan 2": "Refocus",
    "Jenis Sertifikat 2": "Competition certificate ",
    "Jangka Waktu Pelatihan 2": "6 Bulan",
    "Tahun Kerja 1": "2020",
    "Jabatan Kerja 1": "Asisten Ahli Teknik Jalan",
    "Tempat Bekerja 1": "PT Sarana Multi Daya",
    "Tahun Kerja 2": "2023",
    "Jabatan Kerja 2": "Engineering Officer",
    "Tempat Bekerja 2": "PT Hutama Karya (Persero)",
    "Tahun Kerja 3": "",
    "Jabatan Kerja 3": "",
    "Tempat Bekerja 3": "",
    "Tahun Penelitian 1": "2019",
    "Judul Penelitian 1": "Faktor Penyebab Badan Jalan Ambles Ruas Jalan Nasional 086 Batas Kota Sumedang - Cijelag Provinsi Jawa Barat",
    "Peran Penelitian 1": "Ketua",
    "Luaran Penelitian 1": "Skripsi",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "2020",
    "Judul Buku 1": "Penyebab Badan Jalan Nasional Ambles di Provinsi Jawa Barat",
    "Penerbit Buku 1": "Jurnal HPJI Vol.6 No.2 Juli 2020 : 151 - 164",
    "Tahun Buku 2": "2022",
    "Judul Buku 2": "Trase Jalan Lintas Penghubung antara Jalan Lintas Tengah dan Jalan Lintas Selatan Pulau Jawa Berdasarkan Pendekatan Least Cost Path (Studi Kasus : Koridor Trase Kepanjen - Balekambang, Jawa Timur)",
    "Penerbit Buku 2": "Jurnal Transportasi FSTPT",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "2023",
    "Judul Konferensi 1": "Sertifikat Kegagalan Konstruksi",
    "Penyelenggara Konferensi 1": "PU Bangun",
    "Peran Konferensi 1": "Peserta",
    "Tahun Konferensi 2": "2023",
    "Judul Konferensi 2": "Webinar Manajemen Aset Jalan di Indonesia",
    "Penyelenggara Konferensi 2": "Himpunan Pengembang Jalan Indonesia (HPJI)",
    "Peran Konferensi 2": "Panitia",
    "Tahun Konferensi 3": "Seminar Nasional",
    "Judul Konferensi 3": "Seminar Nasional Himpunan Pengembangan Jalan Indonesia (HPJI): Emerging Awareness and Opportunity in Road Infrastructure Management through Digitalization and Integrated Asset Management",
    "Penyelenggara Konferensi 3": "Himpunan Pengembang Jalan Indonesia (HPJI)",
    "Peran Konferensi 3": "Panitia",
    "Tahun Pengabdian 1": "2018",
    "Nama Pengabdian 1": "Teknik Sipil Mengajar",
    "Tempat Pengabdian 1": "Gunung Kidul, DI Yogyakarta",
    "Tahun Pengabdian 2": "2017",
    "Nama Pengabdian 2": "Gerakan Teknik Mengabdi",
    "Tempat Pengabdian 2": "Bantul, DI Yogyakarta",
    "Tahun Penghargaan 1": "2022",
    "Bentuk Penghargaan 1": "Sertifikat Cumlaude",
    "Pemberi Penghargaan 1": "Universitas Gadjah Mada",
    "Tahun Penghargaan 2": "2022",
    "Bentuk Penghargaan 2": "Sertifikat Penghargaan : Lulusan Tercepat Mahasiswa 2020",
    "Pemberi Penghargaan 2": "Fakultas Teknik Universitas Gadjah Mada",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "2016",
    "Nama Organisasi 1": "Civil Foundation",
    "Jabatan Organisasi 1": "Ketua Umum",
    "Tahun Organisasi 2": "2023",
    "Nama Organisasi 2": "Himpunan Pengembangan Jalan Indonesia",
    "Jabatan Organisasi 2": "Anggota",
    "Program Studi": "Teknologi Rekayasa Transportasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.02/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"

  },
  {
    "Nama_Besar": "Yohanes Elia Purwanto",
    "Nama": "Yohanes Elia Purwanto",
    "Nama lengkap beserta gelar": "Yohanes Elia Purwanto, S.T., M.T.",
    "NIP/NIK": "3376011010960004",
    "Tempat Lahir": "Tegal",
    "Tanggal Lahir": "10 Oktober 1996",
    "TTL": "Tegal, 10 Oktober 1996",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Belum kawin",
    "Agama": "Kristen",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Perum Taman Sejahtera gg 5 no 83 Kota Tegal",
    "Facs Rumah": "081218451921",
    "E-Mail": "yohaneseliap@gmail.com",
    "Tahun Lulus 1": "2018",
    "Perguruan Tinggi 1": "Universitas Indonesia",
    "Prodi 1": "Teknik Sipil",
    "Tahun Lulus 2": "2023",
    "Perguruan Tinggi 2": "Universitas Indonesia",
    "Prodi 2": "Teknik Industri (Sistem Produksi & Logistik)",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "",
    "Jenis Pelatihan 1": "",
    "Penyelenggara Pelatihan 1": "",
    "Jenis Sertifikat 1": "",
    "Jangka Waktu Pelatihan 1": "",
    "Tahun Pelatihan 2": "",
    "Jenis Pelatihan 2": "",
    "Penyelenggara Pelatihan 2": "",
    "Jenis Sertifikat 2": "",
    "Jangka Waktu Pelatihan 2": "",
    "Tahun Kerja 1": "2023",
    "Jabatan Kerja 1": "Sales & Marketing Analyst",
    "Tempat Bekerja 1": "BTW",
    "Tahun Kerja 2": "2024",
    "Jabatan Kerja 2": "Logistic Analyst",
    "Tempat Bekerja 2": "PT Solusi Bangun Beton",
    "Tahun Kerja 3": "",
    "Jabatan Kerja 3": "",
    "Tempat Bekerja 3": "",
    "Tahun Penelitian 1": "2018",
    "Judul Penelitian 1": "Analysis on critical gap for pedestrian crossing at Gandul intersection leg",
    "Peran Penelitian 1": "Anggota",
    "Luaran Penelitian 1": "Paper - Conference",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "",
    "Judul Buku 1": "",
    "Penerbit Buku 1": "",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "",
    "Judul Konferensi 1": "",
    "Penyelenggara Konferensi 1": "",
    "Peran Konferensi 1": "",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "2023",
    "Bentuk Penghargaan 1": "Best Research Paper",
    "Pemberi Penghargaan 1": "ICMCER",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Teknologi Rekayasa Transportasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.03/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "I Made Kresna Dana",
    "Nama": "I Made Kresna Dana",
    "Nama lengkap beserta gelar": "I Made Kresna Dana, S.Kom., M.Kom.",
    "NIP/NIK": "5107010111960002",
    "Tempat Lahir": "Denpasar",
    "Tanggal Lahir": "01 November 1996",
    "TTL": "Denpasar, 01 November 1996",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Belum kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Dusun Jelantik Kori Batu Desa Tojan, Klungkung Bali",
    "Facs Rumah": "087855890880",
    "E-Mail": "kresna.dana1@gmail.com",
    "Tahun Lulus 1": "2018",
    "Perguruan Tinggi 1": "STMIK STIKOM Bali",
    "Prodi 1": "Sistem Informasi",
    "Tahun Lulus 2": "2023",
    "Perguruan Tinggi 2": "Universitas Pendidikan Ganesha",
    "Prodi 2": "Ilmu Komputer",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "",
    "Jenis Pelatihan 1": "",
    "Penyelenggara Pelatihan 1": "",
    "Jenis Sertifikat 1": "",
    "Jangka Waktu Pelatihan 1": "",
    "Tahun Pelatihan 2": "",
    "Jenis Pelatihan 2": "",
    "Penyelenggara Pelatihan 2": "",
    "Jenis Sertifikat 2": "",
    "Jangka Waktu Pelatihan 2": "",
    "Tahun Kerja 1": "2018",
    "Jabatan Kerja 1": "Admin Program Studi",
    "Tempat Bekerja 1": "Politeknik Internasional Bali",
    "Tahun Kerja 2": "2022",
    "Jabatan Kerja 2": "Staff Lembaga Penelitian dan Pengabdian Kepada Masyarakat",
    "Tempat Bekerja 2": "Politeknik Internasional Bali",
    "Tahun Kerja 3": "",
    "Jabatan Kerja 3": "",
    "Tempat Bekerja 3": "",
    "Tahun Penelitian 1": "2018",
    "Judul Penelitian 1": "Virtual Tour Creator Berbasis Website",
    "Peran Penelitian 1": "Ketua",
    "Luaran Penelitian 1": "",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "",
    "Judul Buku 1": "",
    "Penerbit Buku 1": "",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "",
    "Judul Konferensi 1": "",
    "Penyelenggara Konferensi 1": "",
    "Peran Konferensi 1": "",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Keamanan Sistem Informasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.04/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "I Gede Putu Megayasa",
    "Nama": "I Gede Putu Megayasa",
    "Nama lengkap beserta gelar": "I Gede Putu Megayasa, S.Kom., M.Kom.",
    "NIP/NIK": "1733746647130152",
    "Tempat Lahir": "",
    "Tanggal Lahir": "01 April 1968",
    "TTL": "01 April 1968",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Banjar Karang Suwung sading, Gang Batur Sari 09 Mengwi ",
    "Facs Rumah": "08155725094",
    "E-Mail": "megayasaku@gmail.com",
    "Tahun Lulus 1": "1998",
    "Perguruan Tinggi 1": "University Kristen Duta Wacana Yogyakarta ",
    "Prodi 1": "Teknik Informatika",
    "Tahun Lulus 2": "2019",
    "Perguruan Tinggi 2": "Undiksha singaraja",
    "Prodi 2": "Ilkom",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "",
    "Jenis Pelatihan 1": "",
    "Penyelenggara Pelatihan 1": "",
    "Jenis Sertifikat 1": "",
    "Jangka Waktu Pelatihan 1": "",
    "Tahun Pelatihan 2": "",
    "Jenis Pelatihan 2": "",
    "Penyelenggara Pelatihan 2": "",
    "Jenis Sertifikat 2": "",
    "Jangka Waktu Pelatihan 2": "",
    "Tahun Kerja 1": "",
    "Jabatan Kerja 1": "",
    "Tempat Bekerja 1": "",
    "Tahun Kerja 2": "",
    "Jabatan Kerja 2": "",
    "Tempat Bekerja 2": "",
    "Tahun Kerja 3": "",
    "Jabatan Kerja 3": "",
    "Tempat Bekerja 3": "",
    "Tahun Penelitian 1": "",
    "Judul Penelitian 1": "",
    "Peran Penelitian 1": "",
    "Luaran Penelitian 1": "",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "",
    "Judul Buku 1": "",
    "Penerbit Buku 1": "",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "",
    "Judul Konferensi 1": "",
    "Penyelenggara Konferensi 1": "",
    "Peran Konferensi 1": "",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Keamanan Sistem Informasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tidak Tetap",
    "Status Caps": "TIDAK TETAP",
    "Nomor SK": "NOMOR: SK.05/Y-BTW/XI/2024",
    "Jabatan": "-"
  },
  {
    "Nama_Besar": "Ni Luh Widi Rahayu",
    "Nama": "Ni Luh Widi Rahayu",
    "Nama lengkap beserta gelar": "Ni Luh Widi Rahayu, S.Kom., M.T",
    "NIP/NIK": "5103045010970001",
    "Tempat Lahir": "Badung",
    "Tanggal Lahir": "10 Oktober 1997",
    "TTL": "Badung, 10 Oktober 1997",
    "Jenis Kelamin": "Perempuan",
    "Status Perkawinan": "Belum kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Br. Sidan, Desa Belok / Sidan, Kec. Petang, Kab. Badung",
    "Facs Rumah": "08983161086",
    "E-Mail": "luhwidirahayu@gmail.com",
    "Tahun Lulus 1": "2019",
    "Perguruan Tinggi 1": "Institut Bisnis dan Teknologi Indonesia",
    "Prodi 1": "Teknik Informatika ",
    "Tahun Lulus 2": "2024",
    "Perguruan Tinggi 2": "Universitas Udayana",
    "Prodi 2": "Manajemen Sistem Informasi dan Komputer ",
    "Tahun Lulus 3": "-",
    "Perguruan Tinggi 3": "-",
    "Prodi 3": "-",
    "Tahun Pelatihan 1": "-",
    "Jenis Pelatihan 1": "",
    "Penyelenggara Pelatihan 1": "",
    "Jenis Sertifikat 1": "",
    "Jangka Waktu Pelatihan 1": "",
    "Tahun Pelatihan 2": "",
    "Jenis Pelatihan 2": "",
    "Penyelenggara Pelatihan 2": "",
    "Jenis Sertifikat 2": "",
    "Jangka Waktu Pelatihan 2": "",
    "Tahun Kerja 1": "2019",
    "Jabatan Kerja 1": "Sekretasi Inkubator Bisnis INSTIKI",
    "Tempat Bekerja 1": "Kampus INSTIKI",
    "Tahun Kerja 2": "2022",
    "Jabatan Kerja 2": "Staff Akademik KPTA",
    "Tempat Bekerja 2": "Kampus INSTIKI",
    "Tahun Kerja 3": "2024",
    "Jabatan Kerja 3": "Staff Dekan Fakultas Bisnis dan Desain Kreatif",
    "Tempat Bekerja 3": "Kampus INSTIKI",
    "Tahun Penelitian 1": "2024",
    "Judul Penelitian 1": "Klasifikasi Jajanan Khas Bali Untuk Preservasi Pengetahuan Kuliner Lokal Menggunakan Arsitektur VGG-16",
    "Peran Penelitian 1": "Ketua",
    "Luaran Penelitian 1": "Jurnal Ilmiah",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "2024",
    "Judul Buku 1": "Klasifikasi Jajanan Khas Bali Untuk Preservasi Pengetahuan Kuliner Lokal Menggunakan Arsitektur VGG-16",
    "Penerbit Buku 1": "SINTECH",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "",
    "Judul Konferensi 1": "",
    "Penyelenggara Konferensi 1": "",
    "Peran Konferensi 1": "",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Kecerdasan Buatan dan Robotik",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.06/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "Dhruvayoti Tiirtheshvara",
    "Nama": "Dhruvayoti Tiirtheshvara",
    "Nama lengkap beserta gelar": "Dhruvayoti Tiirtheshvara, S.Kom., M.Kom.",
    "NIP/NIK": "5108072104990002",
    "Tempat Lahir": "Denpasar",
    "Tanggal Lahir": "21 April 1999",
    "TTL": "Denpasar, 21 April 1999",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Belum kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Perum grahasinar rahayu blok D no 8",
    "Facs Rumah": "082147150297",
    "E-Mail": "tirthashvara@gmail.com",
    "Tahun Lulus 1": "2022",
    "Perguruan Tinggi 1": "Institut Teknologi dan Bisnis STIKOM BALI",
    "Prodi 1": "SISTEM KOMPUTER",
    "Tahun Lulus 2": "2025",
    "Perguruan Tinggi 2": "Universitas Pendidikan Ganesha ",
    "Prodi 2": "ILMU KOMPUTER",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "",
    "Jenis Pelatihan 1": "",
    "Penyelenggara Pelatihan 1": "",
    "Jenis Sertifikat 1": "",
    "Jangka Waktu Pelatihan 1": "",
    "Tahun Pelatihan 2": "",
    "Jenis Pelatihan 2": "",
    "Penyelenggara Pelatihan 2": "",
    "Jenis Sertifikat 2": "",
    "Jangka Waktu Pelatihan 2": "",
    "Tahun Kerja 1": "2019",
    "Jabatan Kerja 1": "Frontend developer ",
    "Tempat Bekerja 1": "Freelance ",
    "Tahun Kerja 2": "2020",
    "Jabatan Kerja 2": "Operator dapodik",
    "Tempat Bekerja 2": "TK SAIWA DHARMA BANYUNING",
    "Tahun Kerja 3": "2022",
    "Jabatan Kerja 3": "Wakil kepala sekolah bidang kesiswaan, Guru, kaprodi Rekayasa perangkat lunak ",
    "Tempat Bekerja 3": "SMK TI Bali Global Singaraja ",
    "Tahun Penelitian 1": "2024",
    "Judul Penelitian 1": "The Impact Off The QUIZZIZ Application on Students Self-efficacy",
    "Peran Penelitian 1": "Anggota",
    "Luaran Penelitian 1": "JPPIPA",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "",
    "Judul Buku 1": "",
    "Penerbit Buku 1": "",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "",
    "Judul Konferensi 1": "",
    "Penyelenggara Konferensi 1": "",
    "Peran Konferensi 1": "",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "2023",
    "Bentuk Penghargaan 1": "Sertifikat Traning Projek Kreatif dan Kewirausahaan (PKK)",
    "Pemberi Penghargaan 1": "SEAMEO QITEP IN SCIENCE ORGANISASI",
    "Tahun Penghargaan 2": "2024",
    "Bentuk Penghargaan 2": "Sertifikat Pembina LKS Provinsi Bali ",
    "Pemberi Penghargaan 2": "Disdikpora Provinsi Bali",
    "Tahun Penghargaan 3": "2024",
    "Bentuk Penghargaan 3": "Sertifikat Pembina LKS Nasional Tingkat SMK Se Indonesia ",
    "Pemberi Penghargaan 3": "Disdikpora Pusat ",
    "Tahun Organisasi 1": "2023",
    "Nama Organisasi 1": "YAYASAN SAIWA DHARMA INDONESIA",
    "Jabatan Organisasi 1": "Sekretaris ",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Keamanan Sistem Informasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.07/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "Ni Nyoman Murni",
    "Nama": "Ni Nyoman Murni",
    "Nama lengkap beserta gelar": "Ni Nyoman Murni, S.Kom., M.Kom.",
    "NIP/NIK": "5104014201890002",
    "Tempat Lahir": "Sukawati",
    "Tanggal Lahir": "02 Januari 1989",
    "TTL": "Sukawati, 02 Januari 1989",
    "Jenis Kelamin": "Perempuan",
    "Status Perkawinan": "Kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "BR. Petangan Gede Ubung Kaja Denpasar Utara",
    "Facs Rumah": "08124691283",
    "E-Mail": "nyomanmurni.ilkom@gmail.com",
    "Tahun Lulus 1": "2012",
    "Perguruan Tinggi 1": "ITB STIKOM Bali",
    "Prodi 1": "Sistem Komputer",
    "Tahun Lulus 2": "2023",
    "Perguruan Tinggi 2": "Universitas Pendidikan Ganesha",
    "Prodi 2": "Ilmu Komputer",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "2024",
    "Jenis Pelatihan 1": "Dalam Negeri",
    "Penyelenggara Pelatihan 1": "Axioo",
    "Jenis Sertifikat 1": "Workshop",
    "Jangka Waktu Pelatihan 1": "1 hari ",
    "Tahun Pelatihan 2": "",
    "Jenis Pelatihan 2": "",
    "Penyelenggara Pelatihan 2": "",
    "Jenis Sertifikat 2": "",
    "Jangka Waktu Pelatihan 2": "",
    "Tahun Kerja 1": "2012",
    "Jabatan Kerja 1": "Guru",
    "Tempat Bekerja 1": "SMK TI Bali Global Badung",
    "Tahun Kerja 2": "",
    "Jabatan Kerja 2": "",
    "Tempat Bekerja 2": "",
    "Tahun Kerja 3": "",
    "Jabatan Kerja 3": "",
    "Tempat Bekerja 3": "",
    "Tahun Penelitian 1": "2023",
    "Judul Penelitian 1": "Implementasi Metode Fuzzy Analytica Hierarchy Process (FAHP) Dalam\nPenentuan Bobot Seleksi Mahasiswa Program Pendidikan Dokter Spesialis",
    "Peran Penelitian 1": "Ketua",
    "Luaran Penelitian 1": "https://jurnal.stts.edu/index.php/INSYST/article/view/321",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "",
    "Judul Buku 1": "",
    "Penerbit Buku 1": "",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "",
    "Judul Konferensi 1": "",
    "Penyelenggara Konferensi 1": "",
    "Peran Konferensi 1": "",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Keamanan Sistem Informasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.08/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "Made Widya Nugraha", 
    "Nama": "Made Widya Nugraha",
    "Nama lengkap beserta gelar": "Made Widya Nugraha, S.T., M.Eng.",
    "NIP/NIK": "3471112804980001",
    "Tempat Lahir": "Australia",
    "Tanggal Lahir": "28 April 1998",
    "TTL": "Australia, 28 April 1998",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Belum kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Jl. Anggrek No.9, Dangin Puri Kangin, Denpasar Utara, Bali",
    "Facs Rumah": "+6281239835257",
    "E-Mail": "madewidyan@gmail.com",
    "Tahun Lulus 1": "2020",
    "Perguruan Tinggi 1": "Universitas Gadjah Mada",
    "Prodi 1": "Teknik Sipil",
    "Tahun Lulus 2": "2023",
    "Perguruan Tinggi 2": "Seoul National University of Science and Technology",
    "Prodi 2": "Railway Engineering",
    "Tahun Lulus 3": "-",
    "Perguruan Tinggi 3": "-",
    "Prodi 3": "-",
    "Tahun Pelatihan 1": "2020",
    "Jenis Pelatihan 1": "Dalam Negeri",
    "Penyelenggara Pelatihan 1": "Direktorat Jendral Bina Konstruksi - Kementrian PUPR",
    "Jenis Sertifikat 1": "Ahli Muda K-3 Konstruksi",
    "Jangka Waktu Pelatihan 1": "-",
    "Tahun Pelatihan 2": "2024",
    "Jenis Pelatihan 2": "Dalam Negeri",
    "Penyelenggara Pelatihan 2": "Politeknik Negeri Bali",
    "Jenis Sertifikat 2": "Sertifikat TOEFL (Score: 593)",
    "Jangka Waktu Pelatihan 2": "-",
    "Tahun Kerja 1": "2020",
    "Jabatan Kerja 1": "Tenaga Teknik Sipil",
    "Tempat Bekerja 1": "Dinas Perhubungan Provinsi Bali",
    "Tahun Kerja 2": "2023",
    "Jabatan Kerja 2": "Tenaga Ahli Konsultan - Data Analis",
    "Tempat Bekerja 2": "Badan Perencanaan Pembangunan Nasional (Bappenas)",
    "Tahun Kerja 3": "-",
    "Jabatan Kerja 3": "",
    "Tempat Bekerja 3": "",
    "Tahun Penelitian 1": "",
    "Judul Penelitian 1": "",
    "Peran Penelitian 1": "",
    "Luaran Penelitian 1": "",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "2020",
    "Judul Buku 1": "Prediksi Arus Lalu Lintas Serta Dampaknya Pada Kinerja Jalan Tol ( Studi Kasus : Jalan Tol Semarang - Solo Seksi I)",
    "Penerbit Buku 1": "Fakultas Teknik Universitas Gadjah Mada",
    "Tahun Buku 2": "2023",
    "Judul Buku 2": "Track Widening on Curved Track Analysis ( Case Study : Bali LRT Project)",
    "Penerbit Buku 2": "Department of Railway Construction Engineering",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "",
    "Judul Konferensi 1": "",
    "Penyelenggara Konferensi 1": "",
    "Peran Konferensi 1": "",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Teknologi Rekayasa Transportasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.09/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "Ni Putu Eka Apriyanthi",
    "Nama": "Ni Putu Eka Apriyanthi",
    "Nama lengkap beserta gelar": "Ni Putu Eka Apriyanthi, S.Kom., M.Kom.",
    "NIP/NIK": "5102024104920002",
    "Tempat Lahir": "Denpasar",
    "Tanggal Lahir": "01 April 1992",
    "TTL": "Denpasar, 01 April 1992",
    "Jenis Kelamin": "Perempuan",
    "Status Perkawinan": "Kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Jalan Tukad Selabih, Blok 20 , No.09 Perum Sanggulan, Kediri, Tabanan",
    "Facs Rumah": "082113112711",
    "E-Mail": "eapriyanthi@gmail.com",
    "Tahun Lulus 1": "2022",
    "Perguruan Tinggi 1": "STMIK Primakara",
    "Prodi 1": "Sistem Informasi Akuntansi",
    "Tahun Lulus 2": "2024",
    "Perguruan Tinggi 2": "Universitas Pendidikan Ganesha",
    "Prodi 2": "Ilmu Komputer",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "",
    "Jenis Pelatihan 1": "",
    "Penyelenggara Pelatihan 1": "",
    "Jenis Sertifikat 1": "",
    "Jangka Waktu Pelatihan 1": "",
    "Tahun Pelatihan 2": "",
    "Jenis Pelatihan 2": "",
    "Penyelenggara Pelatihan 2": "",
    "Jenis Sertifikat 2": "",
    "Jangka Waktu Pelatihan 2": "",
    "Tahun Kerja 1": "2011 - 2019",
    "Jabatan Kerja 1": "Personalia, Keuangan",
    "Tempat Bekerja 1": "Bali Maritime Training Center",
    "Tahun Kerja 2": "2020 - 2022",
    "Jabatan Kerja 2": "Quality Management Representative",
    "Tempat Bekerja 2": "Asta Maritim Indonesia",
    "Tahun Kerja 3": "2022 - Sekarang",
    "Jabatan Kerja 3": "Operasional Manager",
    "Tempat Bekerja 3": "PT Safaga Apta Prapti",
    "Tahun Penelitian 1": "",
    "Judul Penelitian 1": "",
    "Peran Penelitian 1": "",
    "Luaran Penelitian 1": "",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "2022",
    "Judul Buku 1": "Analisa Nilai Valuasi Perusahaan Startup: Studi Kasus XYZ Digital Informasi",
    "Penerbit Buku 1": "JURNAL EKONOMI BISNIS VOL 21 NO 1 : 39 – 48",
    "Tahun Buku 2": "2024",
    "Judul Buku 2": "Evaluasi Usability Dengan Pendekatan System Usability Scale (SUS) Pada Aplikasi TMHub",
    "Penerbit Buku 2": "Vol 7, No 3 (2024): JTKSI (Jurnal Teknologi Komputer dan Sistem Informasi)",
    "Tahun Buku 3": "2024",
    "Judul Buku 3": "Analysis Of Webqual 4.0 And Cognitive Walkthrough Methods On CTI Govideo Spark Hire Online Interview Application",
    "Penerbit Buku 3": "Jurnal Teknik Informatika (JUTIF)",
    "Tahun Makalah 1": "2024",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "2024",
    "Judul Konferensi 1": "SENIKO (Seminar Nasional Informatika dan Komputer)",
    "Penyelenggara Konferensi 1": "Universitas Jenderal Soedirman (UNSOED)",
    "Peran Konferensi 1": "Pembicara",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "Bali Start Up Camp 2020",
    "Bentuk Penghargaan 1": "Juara III",
    "Pemberi Penghargaan 1": "STMIK Primakara",
    "Tahun Penghargaan 2": "Lomba Digitalpreneurship Perguruan Tinggi se Bali Nusra",
    "Bentuk Penghargaan 2": "Juara III",
    "Pemberi Penghargaan 2": "Bank Indonesia",
    "Tahun Penghargaan 3": "Kompetisi Bisnis Mahasiswa Indonesia (KBMI)",
    "Bentuk Penghargaan 3": "Tim Berprestasi STMIK Primakara",
    "Pemberi Penghargaan 3": "Direktorat Pembelajaran dan Kemahasiswaan, Direktorat Jenderal Pendidikan Tinggi, Kemendikbud",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Keamanan Sistem Informasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.10/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "Nugroho Suadi, A.TD, MT",
    "Nama": "Nugroho Suadi, A.TD, MT",
    "Nama lengkap beserta gelar": "Nugroho Suadi, A.TD, MT",
    "NIP/NIK": "337413301157",
    "Tempat Lahir": "Semarang",
    "Tanggal Lahir": "30 November 1957",
    "TTL": "Semarang, 30 November 1957",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Kawin",
    "Agama": "Islam",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Jl.Pala 27 Perumahan Shangrila-Land Ruko B/6-Desa Dampyak,Kecamatan Kramat Kabupaten Tegal-Jateng.",
    "Facs Rumah": "081225122853",
    "E-Mail": "suadinugroho@gmail.com",
    "Tahun Lulus 1": "1994",
    "Perguruan Tinggi 1": "PTDI-STTD Bekasi",
    "Prodi 1": "Diploma IV Transportasi Darat",
    "Tahun Lulus 2": "2004",
    "Perguruan Tinggi 2": "Universitas Diponegoro, Program Magister Teknik.Sipil, Konsentrasi Transportasi",
    "Prodi 2": "Magistet Teknik.Sipil, Konsentrasi Transportasi",
    "Tahun Lulus 3": "-",
    "Perguruan Tinggi 3": "-",
    "Prodi 3": "-",
    "Tahun Pelatihan 1": "1.2013.Capacity Building Program on Public for Transport for Officials of The Ministry of Transport (MOT) In Indonesia, ",
    "Jenis Pelatihan 1": "Luar Negeri",
    "Penyelenggara Pelatihan 1": "1.Ministry ofvTransportation Republik of Indonesia Universitas Gajahmada and The Korea Transports Institute( KOTI) ",
    "Jenis Sertifikat 1": "1.Sertifikat Pelatihan;",
    "Jangka Waktu Pelatihan 1": "1. 7 hari",
    "Tahun Pelatihan 2": "1. Tahun 2016",
    "Jenis Pelatihan 2": "Dalam Negeri",
    "Penyelenggara Pelatihan 2": "1.Kepala Balai Pendidikan dan Pelatihan Transpoetasi Darat Bali",
    "Jenis Sertifikat 2": "1.Sertifikat Pelatihan Pendidikan Intelliget Transport System;",
    "Jangka Waktu Pelatihan 2": "1. 5 (lima) hari;",
    "Tahun Kerja 1": "1. Tahun 2006 ssmpai fengan 2012",
    "Jabatan Kerja 1": "Widyaiswara Madya",
    "Tempat Bekerja 1": "Badan Diklat Provinsi JawaTengah",
    "Tahun Kerja 2": "Dosen PKTJ Tegal",
    "Jabatan Kerja 2": "Lektor",
    "Tempat Bekerja 2": "PKTJ Tegal",
    "Tahun Kerja 3": "Dosen PTDI-STTD Bekasi",
    "Jabatan Kerja 3": "1. Tahun 2023",
    "Tempat Bekerja 3": "Dosen PTDI STTD",
    "Tahun Penelitian 1": "1. Tahun 2013",
    "Judul Penelitian 1": "Analisis Perilaku Penyeberang Jalan Terhadap Konflik Lalu Lintas ",
    "Peran Penelitian 1": "Ketua",
    "Luaran Penelitian 1": "Studi Kasus Pada Ruas Jalan SMP 7 Dan DMP 10 Tegal",
    "Tahun Penelitian 2": "1. Tahun 2020",
    "Judul Penelitian 2": "Evaluasi Program Rencana Umum Nasional Keselamatan (RUNK) Berdasarkan Metode Analytic NetworkProcess (ANP)",
    "Peran Penelitian 2": "Ketua",
    "Luaran Penelitian 2": "Kinerja Penyelenggaraan RUNKLLAJ Di Kota Madiun",
    "Tahun Buku 1": "2013",
    "Judul Buku 1": "Analisis Perilaku Pebteberang Jalan Terhadap Konflik Lalu Lintas",
    "Penerbit Buku 1": "PKTJ Tegal",
    "Tahun Buku 2": "1. Tahun 2019",
    "Judul Buku 2": "Kajian Kinerja Prasarana Lalu Lintas Angkutan Jalan Yang Berkeselamatan Menggunakan Metide Hazard Identification, Risk Assesment, And Risk Control ( HIRARC)",
    "Penerbit Buku 2": "PKTJ Tegal",
    "Tahun Buku 3": "1. Tahun 2020",
    "Judul Buku 3": "Evaluasi Pfogram Rencana  Nasional Keselamatan (RUNK) Betdasarkan Metode Analytic Network Process (ANP)",
    "Penerbit Buku 3": "PKTJ Tegal",
    "Tahun Makalah 1": "1. Tahun 2019",
    "Judul Makalah 1": "Prasarana Lalu Lintas dan Angkutan Umum",
    "Penyelenggara Makalah 1": "PKTJ Tegal",
    "Tahun Makalah 2": "1. Tahun 2019",
    "Judul Makalah 2": "Analisa Penilaian Risiko Keselamatan Jalan Di Jalur Pariwisata",
    "Penyelenggara Makalah 2": "PKTJ Tegal",
    "Tahun Makalah 3": "2019",
    "Judul Makalah 3": "Analisis Faktor Pelayanan Ditinjau Dari Aspek Keselamatan PDa Terminal Tipe B",
    "Penyelenggara Makalah 3": "PKTJ Tegal",
    "Tahun Konferensi 1": "2013",
    "Judul Konferensi 1": "Training course in Operation, Calibration, Maintenance and Processing of  data frombthevARRB 2000 Network Survey  Vehicle",
    "Penyelenggara Konferensi 1": "ARRB GROUP LTD, MELBOURNE AUSTRALI",
    "Peran Konferensi 1": "Peserta",
    "Tahun Konferensi 2": "2018",
    "Judul Konferensi 2": "Sinergi Politeknik Keselamatan Transpirtasi Jalan (PKTJ) Tegak dengan Stakeholder dalam Mewujudkan Aksi Keselamatan",
    "Penyelenggara Konferensi 2": "PKTJ Tegal",
    "Peran Konferensi 2": "Panitia",
    "Tahun Konferensi 3": "2000",
    "Judul Konferensi 3": "The Organizing Comittee of 3 rd Simposium of Indonesia Inter University Transportation Studies Forum (FSTPT)",
    "Penyelenggara Konferensi 3": "Unversitas Gadjah Mada",
    "Peran Konferensi 3": "Peserta",
    "Tahun Pengabdian 1": "2013",
    "Nama Pengabdian 1": "Posko Mudik Lebaran Tahun 2013",
    "Tempat Pengabdian 1": "Pekalongan",
    "Tahun Pengabdian 2": "2013",
    "Nama Pengabdian 2": "Penunjukan Dewan Kehormatan Taruna",
    "Tempat Pengabdian 2": "PKTJ TEGAL",
    "Tahun Penghargaan 1": "2003",
    "Bentuk Penghargaan 1": "Penghargaan Karya Satya Lencana XX",
    "Pemberi Penghargaan 1": "Presiden RI ke V.Megawati Soekarno Putri",
    "Tahun Penghargaan 2": "2017",
    "Bentuk Penghargaan 2": "Penghargaan Karya Satya Lencana XXX",
    "Pemberi Penghargaan 2": "Presiden RI ke VII .Joko Widodo",
    "Tahun Penghargaan 3": "-",
    "Bentuk Penghargaan 3": "-",
    "Pemberi Penghargaan 3": "-",
    "Tahun Organisasi 1": "2000",
    "Nama Organisasi 1": "IKAALL PUSAT",
    "Jabatan Organisasi 1": "DEWAN PERTIMBANGAN ORGANISASI PUSAT",
    "Tahun Organisasi 2": "2023",
    "Nama Organisasi 2": "IKAALL JATENG",
    "Jabatan Organisasi 2": "Pengurus IKAALL JATENG",
    "Program Studi": "Teknologi Rekayasa Transportasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tidak Tetap",
    "Status Caps": "TIDAK TETAP",
    "Nomor SK": "NOMOR: SK.11/Y-BTW/XI/2024",
    "Jabatan": "-"
  },
  {
    "Nama_Besar": "Ida Bagus Gede Arsa Wedhana, S.Kom., MM.",
    "Nama": "Ida Bagus Gede Arsa Wedhana, S.Kom., MM.",
    "Nama lengkap beserta gelar": "Ida Bagus Gede Arsa Wedhana, S.Kom., MM.",
    "NIP/NIK": "5171011901900003",
    "Tempat Lahir": "Denpasar",
    "Tanggal Lahir": "19 Januari 1990",
    "TTL": "Denpasar, 19 Januari 1990",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "JL. Waturenggong No. 46 Tegal Sari, Panjer, Denpasar Selatan",
    "Facs Rumah": "081934300772",
    "E-Mail": "ib.arsawedhana@gmail.com",
    "Tahun Lulus 1": "2013",
    "Perguruan Tinggi 1": "Universitas Udayana",
    "Prodi 1": "Ilmu Komputer/Teknik Informatika",
    "Tahun Lulus 2": "2022",
    "Perguruan Tinggi 2": "Universitas Pendidikan Nasional ",
    "Prodi 2": "Magister Manajemen ",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "",
    "Jenis Pelatihan 1": "",
    "Penyelenggara Pelatihan 1": "",
    "Jenis Sertifikat 1": "",
    "Jangka Waktu Pelatihan 1": "",
    "Tahun Pelatihan 2": "",
    "Jenis Pelatihan 2": "",
    "Penyelenggara Pelatihan 2": "",
    "Jenis Sertifikat 2": "",
    "Jangka Waktu Pelatihan 2": "",
    "Tahun Kerja 1": "2014",
    "Jabatan Kerja 1": "IT Support ",
    "Tempat Bekerja 1": "PT. Sunlife Financial Indonesia",
    "Tahun Kerja 2": "2015",
    "Jabatan Kerja 2": "Tenaga Administrasi ",
    "Tempat Bekerja 2": "UPTD. Trans Bali/Trans SARBAGITA Dinas Perhubungan Provinsi Bali",
    "Tahun Kerja 3": "",
    "Jabatan Kerja 3": "",
    "Tempat Bekerja 3": "",
    "Tahun Penelitian 1": "",
    "Judul Penelitian 1": "",
    "Peran Penelitian 1": "",
    "Luaran Penelitian 1": "",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "",
    "Judul Buku 1": "",
    "Penerbit Buku 1": "",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "",
    "Judul Konferensi 1": "",
    "Penyelenggara Konferensi 1": "",
    "Peran Konferensi 1": "",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Kecerdasan Buatan dan Robotik",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.12/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "I Made Adi Sasmita",
    "Nama": "I Made Adi Sasmita",
    "Nama lengkap beserta gelar": "I Made Adi Sasmita, S.Kom., M.Kom.",
    "NIP/NIK": "5103031711000004",
    "Tempat Lahir": "Abiansemal",
    "Tanggal Lahir": "17 November 2000",
    "TTL": "Abiansemal, 17 November 2000",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Belum kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Desa Taman, Kec. Abiansemal, Kab. Badung, Bali",
    "Facs Rumah": "083114490474",
    "E-Mail": "deoyik.nov11@gmail.com",
    "Tahun Lulus 1": "2023",
    "Perguruan Tinggi 1": "Institut Bisnis dan Teknologi Indonesia (INSTIKI)",
    "Prodi 1": "Teknik Informatika",
    "Tahun Lulus 2": "2025",
    "Perguruan Tinggi 2": "Universitas Pendidikan Ganesha",
    "Prodi 2": "Ilmu Komputer",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "",
    "Jenis Pelatihan 1": "",
    "Penyelenggara Pelatihan 1": "",
    "Jenis Sertifikat 1": "",
    "Jangka Waktu Pelatihan 1": "",
    "Tahun Pelatihan 2": "",
    "Jenis Pelatihan 2": "",
    "Penyelenggara Pelatihan 2": "",
    "Jenis Sertifikat 2": "",
    "Jangka Waktu Pelatihan 2": "",
    "Tahun Kerja 1": "2021",
    "Jabatan Kerja 1": "Koordinator Internal Sistem (IT)",
    "Tempat Bekerja 1": "PT. Jinom Network Indonesia",
    "Tahun Kerja 2": "",
    "Jabatan Kerja 2": "",
    "Tempat Bekerja 2": "",
    "Tahun Kerja 3": "",
    "Jabatan Kerja 3": "",
    "Tempat Bekerja 3": "",
    "Tahun Penelitian 1": "",
    "Judul Penelitian 1": "",
    "Peran Penelitian 1": "",
    "Luaran Penelitian 1": "",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "",
    "Judul Buku 1": "",
    "Penerbit Buku 1": "",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "",
    "Judul Konferensi 1": "",
    "Penyelenggara Konferensi 1": "",
    "Peran Konferensi 1": "",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Kecerdasan Buatan dan Robotik",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.13/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "Mohamad Sofyan",
    "Nama": "Mohamad Sofyan",
    "Nama lengkap beserta gelar": "Mohamad Sofyan, S.Tr.T., M.Urb.",
    "NIP/NIK": "196904201991031013",
    "Tempat Lahir": "Jakarta",
    "Tanggal Lahir": "20 April 1969",
    "TTL": "Jakarta, 20 April 1969",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Kawin",
    "Agama": "Islam",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Jl. Segara Mertha Gg. Meteo II no.19",
    "Facs Rumah": "081338204244",
    "E-Mail": "m_ianza@yahoo.co.id",
    "Tahun Lulus 1": "1996",
    "Perguruan Tinggi 1": "Balai Diklat Transportasi Darat",
    "Prodi 1": "Transportasi Darat",
    "Tahun Lulus 2": "2000",
    "Perguruan Tinggi 2": "Universitas Paris XII, Perancis",
    "Prodi 2": "URBANISME",
    "Tahun Lulus 3": "-",
    "Perguruan Tinggi 3": "-",
    "Prodi 3": "-",
    "Tahun Pelatihan 1": "Sustainable Urban Transport",
    "Jenis Pelatihan 1": "Luar Negeri",
    "Penyelenggara Pelatihan 1": "University of Hiroshima",
    "Jenis Sertifikat 1": "Short Course",
    "Jangka Waktu Pelatihan 1": "7 hari",
    "Tahun Pelatihan 2": "ITS Technology",
    "Jenis Pelatihan 2": "Luar Negeri",
    "Penyelenggara Pelatihan 2": "ITS Korea",
    "Jenis Sertifikat 2": "Short Course",
    "Jangka Waktu Pelatihan 2": "7 hari",
    "Tahun Kerja 1": "Kanwil Dephub. Prov. Bali",
    "Jabatan Kerja 1": "Staf",
    "Tempat Bekerja 1": "Denpasar, Bali",
    "Tahun Kerja 2": "2009",
    "Jabatan Kerja 2": "Kasi MRLL",
    "Tempat Bekerja 2": "Dinas Perhubungan Provinsi Bali",
    "Tahun Kerja 3": "2021",
    "Jabatan Kerja 3": "Ka..UPTD Pusat Pengendalian LLAJ",
    "Tempat Bekerja 3": "Dishub. Prov. Bali",
    "Tahun Penelitian 1": "2007",
    "Judul Penelitian 1": "Penyusunan Master Plan Transportasi Bali",
    "Peran Penelitian 1": "Anggota",
    "Luaran Penelitian 1": "Dokumen Induk Perencanaan Transportasi Bali",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "",
    "Judul Buku 1": "",
    "Penerbit Buku 1": "",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "2020",
    "Judul Konferensi 1": "Traffic Safety Riding",
    "Penyelenggara Konferensi 1": "Poltek Negeri Bali",
    "Peran Konferensi 1": "Pembicara",
    "Tahun Konferensi 2": "2020",
    "Judul Konferensi 2": "The Role of Road Safety Audits in Improving Traffic Safety",
    "Penyelenggara Konferensi 2": "International Road Federation",
    "Peran Konferensi 2": "Peserta",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Kecerdasan Buatan dan Robotik",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tidak Tetap",
    "Status Caps": "TIDAK TETAP",
    "Nomor SK": "NOMOR: SK.14/Y-BTW/XI/2024",
    "Jabatan": "-"
  },
  {
    "Nama_Besar": "Sandy Wardhana",
    "Nama": "Sandy Wardhana",
    "Nama lengkap beserta gelar": "Sandy Wardhana, S.Kom., M.Si.",
    "NIP/NIK": "3578021208790001",
    "Tempat Lahir": "Pamekasan",
    "Tanggal Lahir": "12 Agustus 1979",
    "TTL": "Pamekasan, 12 Agustus 1979",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Kawin",
    "Agama": "Kristen",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Jl. Cipinang Cempedak IV no 3D, Jatinegara, Jakarta Timur",
    "Facs Rumah": "081314630883",
    "E-Mail": "sandy.wardhana@gmail.com",
    "Tahun Lulus 1": "2003",
    "Perguruan Tinggi 1": "Institut Teknologi Sepuluh Nopember ",
    "Prodi 1": "Teknik Informatika",
    "Tahun Lulus 2": "2010",
    "Perguruan Tinggi 2": "Universitas Indonesia",
    "Prodi 2": "Kajian Ketahanan Nasional",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "Workshop Modern Project Management",
    "Jenis Pelatihan 1": "Dalam Negeri",
    "Penyelenggara Pelatihan 1": "Indoprime",
    "Jenis Sertifikat 1": "Paper Based",
    "Jangka Waktu Pelatihan 1": "5 hari",
    "Tahun Pelatihan 2": "Penerapan Intelligent Transportation System untuk Mencapai Pengelolaan Sektor Transportasi Modern di Indonesia",
    "Jenis Pelatihan 2": "Dalam Negeri",
    "Penyelenggara Pelatihan 2": "FSTPT",
    "Jenis Sertifikat 2": "Elektronik",
    "Jangka Waktu Pelatihan 2": "1 hari",
    "Tahun Kerja 1": "2003-2010",
    "Jabatan Kerja 1": "Team Leader",
    "Tempat Bekerja 1": "Bank Mandiri",
    "Tahun Kerja 2": "2023-2024",
    "Jabatan Kerja 2": "Direktur",
    "Tempat Bekerja 2": "Roatex Toll Road Indonesia",
    "Tahun Kerja 3": "2024",
    "Jabatan Kerja 3": "Direktur",
    "Tempat Bekerja 3": "Unit Sky Indonesia (MinSky)",
    "Tahun Penelitian 1": "",
    "Judul Penelitian 1": "",
    "Peran Penelitian 1": "",
    "Luaran Penelitian 1": "",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "",
    "Judul Buku 1": "",
    "Penerbit Buku 1": "",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "2024",
    "Judul Konferensi 1": "Managing Traffic Through AI Based Control Technology",
    "Penyelenggara Konferensi 1": "Intelligent Traffic System (ITS) Indonesia",
    "Peran Konferensi 1": "Pembicara",
    "Tahun Konferensi 2": "2024",
    "Judul Konferensi 2": "Penerapan Intelligent Transport System untuk Mencapai Pengelolaan Sektor Transportasi Umum di Indonesia",
    "Penyelenggara Konferensi 2": "FSTPT",
    "Peran Konferensi 2": "Pembicara",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "2023-skrg",
    "Nama Organisasi 1": "Intelligent Transport System (ITS) Indonesia",
    "Jabatan Organisasi 1": "Anggota",
    "Tahun Organisasi 2": "2024",
    "Nama Organisasi 2": "Masyarakat Transportasi Indonesia (MTI)",
    "Jabatan Organisasi 2": "Anggota",
    "Program Studi": "Teknologi Rekayasa Transportasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.15/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "Gd. Aditya Jana Satvika",
    "Nama": "Gd. Aditya Jana Satvika",
    "Nama lengkap beserta gelar": "Gd. Aditya Jana Satvika, S.Kom., M.Kom.",
    "NIP/NIK": "5104030408960002",
    "Tempat Lahir": "Denpasar",
    "Tanggal Lahir": "04 Agustus 1996",
    "TTL": "Denpasar, 04 Agustus 1996",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Belum kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Jl. Pantai Lebih, Banjar Kesian, Desa Lebih, Kec. Gianyar, Bali.",
    "Facs Rumah": "082237446606",
    "E-Mail": "janasatvika8@gmail.com",
    "Tahun Lulus 1": "2018",
    "Perguruan Tinggi 1": "Universitas Telkom",
    "Prodi 1": "Sistem Komputer",
    "Tahun Lulus 2": "2024",
    "Perguruan Tinggi 2": "Universitas Pendidikan Ganesha",
    "Prodi 2": "Ilmu Komputer",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "2022",
    "Jenis Pelatihan 1": "Dalam Negeri",
    "Penyelenggara Pelatihan 1": "Digital Talent Scholarship & Binar Academy",
    "Jenis Sertifikat 1": "Sertifikat Pelatihan",
    "Jangka Waktu Pelatihan 1": "19 September - 16 Oktober 2022 (174 Jam Pelatihan)",
    "Tahun Pelatihan 2": "2023",
    "Jenis Pelatihan 2": "Dalam Negeri",
    "Penyelenggara Pelatihan 2": "Digital Talent Scholarship & DQLab",
    "Jenis Sertifikat 2": "Sertifikat Pelatihan",
    "Jangka Waktu Pelatihan 2": "3 Maret - 14 April 2023 (85 Jam Pelatihan)",
    "Tahun Kerja 1": "2019",
    "Jabatan Kerja 1": "Internship",
    "Tempat Bekerja 1": "Telkom Indonesia (Witel Denpasar - Corporate Customer Access Network (CCAN) division)",
    "Tahun Kerja 2": "2020",
    "Jabatan Kerja 2": "Staff Marketing",
    "Tempat Bekerja 2": "Sekolah Tinggi Manajemen Informatika dan Komputer (STMIK) Primakara / (Sekarang) Primakara University",
    "Tahun Kerja 3": "",
    "Jabatan Kerja 3": "",
    "Tempat Bekerja 3": "",
    "Tahun Penelitian 1": "2018",
    "Judul Penelitian 1": "Determination of the Best Vehicle Pathway with Classification of Data Mining Twitter using K-Nearest Neighbor",
    "Peran Penelitian 1": "",
    "Luaran Penelitian 1": "Conference Paper: 10.1109/ICITSI.2018.8695947",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "2018",
    "Judul Buku 1": "Determination of the Best Vehicle Pathway with Classification of Data Mining Twitter using K-Nearest Neighbor",
    "Penerbit Buku 1": "IEEE",
    "Tahun Buku 2": "2024",
    "Judul Buku 2": "Improving k-nearest neighbor performance using permutation feature importance to predict student success in study",
    "Penerbit Buku 2": "Indonesian Journal of Electrical Engineering and Computer Science",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "2021",
    "Judul Konferensi 1": "Vertical-Horizontal Integration in Industry 4.0",
    "Penyelenggara Konferensi 1": "Institut Teknologi Bandung (ITB)",
    "Peran Konferensi 1": "Peserta",
    "Tahun Konferensi 2": "2022",
    "Judul Konferensi 2": "Sharing Session Pengguna & Alumni: Peluang Pengembangan Riset Ilmu Komputer di Pemerintahan, Industri, dan dunia Pendidikan",
    "Penyelenggara Konferensi 2": "Pascasarjana Universitas Pendidikan Ganesha",
    "Peran Konferensi 2": "Peserta",
    "Tahun Konferensi 3": "2022",
    "Judul Konferensi 3": "Implementasi Kearifan Lokal Pada Penelitian Bidang Ilmu Komputer dan Teknologi Informasi",
    "Penyelenggara Konferensi 3": "Pascasarjana Universitas Pendidikan Ganesha",
    "Peran Konferensi 3": "Peserta",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Keamanan Sistem Informasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.16/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "Gatot Sanjaya",
    "Nama": "Gatot Sanjaya",
    "Nama lengkap beserta gelar": "Gatot Sanjaya, S.T., M.T.",
    "NIP/NIK": "5105031311660002",
    "Tempat Lahir": "Singaraja",
    "Tanggal Lahir": "13 November 1966",
    "TTL": "Singaraja, 13 November 1966",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Jalan Nangka Selatan Gg Merpati No 4/14 Denpasar",
    "Facs Rumah": "08980755353",
    "E-Mail": "gatotsanjaya1966@gmail.com",
    "Tahun Lulus 1": "1966",
    "Perguruan Tinggi 1": "Universitas Dharma Persada di Jakarta",
    "Prodi 1": "Teknik dan Manajemen Industri",
    "Tahun Lulus 2": "2014",
    "Perguruan Tinggi 2": "Universitas Mahasaraswati Denpasar",
    "Prodi 2": "Perencanaan Pembangunan Wilayah dan Pengelolaan Lingkungan",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "1991",
    "Jenis Pelatihan 1": "Dalam Negeri",
    "Penyelenggara Pelatihan 1": "Pendidikan dan Latihan Perhubungan Udara Badan Pendidikan dan Latihan Departemen Perhubungan",
    "Jenis Sertifikat 1": "Penataran Instruktur",
    "Jangka Waktu Pelatihan 1": "165 Jam",
    "Tahun Pelatihan 2": "1995",
    "Jenis Pelatihan 2": "Dalam Negeri",
    "Penyelenggara Pelatihan 2": "Pendidikan dan Latihan Perhubungan Udara Badan Pendidikan dan Latihan Departemen Perhubungan",
    "Jenis Sertifikat 2": "Airport System Planning",
    "Jangka Waktu Pelatihan 2": "143 Jam",
    "Tahun Kerja 1": "1990",
    "Jabatan Kerja 1": "Staf Pendidikan dan Latihan Penerbangan",
    "Tempat Bekerja 1": "Pendidikan dan Latihan Penerbangan",
    "Tahun Kerja 2": "2000",
    "Jabatan Kerja 2": "Staf Bidang Udara",
    "Tempat Bekerja 2": "Kanwil XIV Departemen Perhubungan di Bali",
    "Tahun Kerja 3": "2021",
    "Jabatan Kerja 3": "Staf Bidang Udara",
    "Tempat Bekerja 3": "Dinas Perhubungan Provinsi Bali",
    "Tahun Penelitian 1": "",
    "Judul Penelitian 1": "",
    "Peran Penelitian 1": "",
    "Luaran Penelitian 1": "",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "",
    "Judul Buku 1": "",
    "Penerbit Buku 1": "",
    "Tahun Buku 2": "",
    "Judul Buku 2": "",
    "Penerbit Buku 2": "",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "",
    "Judul Konferensi 1": "",
    "Penyelenggara Konferensi 1": "",
    "Peran Konferensi 1": "",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "",
    "Nama Pengabdian 1": "",
    "Tempat Pengabdian 1": "",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "",
    "Bentuk Penghargaan 1": "",
    "Pemberi Penghargaan 1": "",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Teknologi Rekayasa Transportasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tidak Tetap",
    "Status Caps": "TIDAK TETAP",
    "Nomor SK": "NOMOR: SK.17/Y-BTW/XI/2024",
    "Jabatan": "-"
  },
  {
    "Nama_Besar": "I Made Oka Sugiana, ST., MT.",
    "Nama": "I Made Oka Sugiana, ST., MT.",
    "Nama lengkap beserta gelar": "I Made Oka Sugiana, ST., MT.",
    "NIP/NIK": "510302230390",
    "Tempat Lahir": "Badung",
    "Tanggal Lahir": "23 Maret 1990",
    "TTL": "Badung, 23 Maret 1990",
    "Jenis Kelamin": "Laki - laki",
    "Status Perkawinan": "Kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "JL. I GUSTI KETUT JELANTIK, GANG MELATI NO. 8, BR. BATU, DESA MENGWI, KEC. MENGWI, KAB. BADUNG.",
    "Facs Rumah": "081916405847",
    "E-Mail": "sugianaoka@gmail.com",
    "Tahun Lulus 1": "2013",
    "Perguruan Tinggi 1": "UNIVERSITAS UDAYANA",
    "Prodi 1": "TEKNIK SIPIL",
    "Tahun Lulus 2": "2019",
    "Perguruan Tinggi 2": "UNIVERSITAS UDAYANA",
    "Prodi 2": "MAGISTER TEKNIK SIPIL",
    "Tahun Lulus 3": "-",
    "Perguruan Tinggi 3": "-",
    "Prodi 3": "-",
    "Tahun Pelatihan 1": "2018",
    "Jenis Pelatihan 1": "Dalam Negeri",
    "Penyelenggara Pelatihan 1": "DIREKTORAT JENDRAL PERHUBUNGAN DARAT, KEMENTRIAN PERHUBUNGAN",
    "Jenis Sertifikat 1": "SERTIFIKASI PENYUSUN ANALISIS DAMPAK LALU LINTAS",
    "Jangka Waktu Pelatihan 1": "10 HARI",
    "Tahun Pelatihan 2": "2024",
    "Jenis Pelatihan 2": "Dalam Negeri",
    "Penyelenggara Pelatihan 2": "LEMBAGA SERTIFIKASI PROFESI ASTEKINDO KONSTRUKSI MANDIRI, BADAN NASIONAL SERTIFIKASI PROFESI",
    "Jenis Sertifikat 2": "AHLI MUDA TEKNIK JALAN",
    "Jangka Waktu Pelatihan 2": "3 HARI",
    "Tahun Kerja 1": "2013",
    "Jabatan Kerja 1": "SURVEYOR",
    "Tempat Bekerja 1": "CV. NARARYA CIPTA AMERTA",
    "Tahun Kerja 2": "2015",
    "Jabatan Kerja 2": "ASISTEN AHLI LALU LINTAS",
    "Tempat Bekerja 2": "CV. NARARYA CIPTA AMERTA",
    "Tahun Kerja 3": "-",
    "Jabatan Kerja 3": "-",
    "Tempat Bekerja 3": "-",
    "Tahun Penelitian 1": "2013",
    "Judul Penelitian 1": "STUDI TATRALOK KOTA DENPASAR",
    "Peran Penelitian 1": "Anggota",
    "Luaran Penelitian 1": "DOKUMEN TATRALOK KOTA DENPASAR 2013",
    "Tahun Penelitian 2": "2019",
    "Judul Penelitian 2": "STUDI PERENCANAAN ANGKUTAN SISWA KABUPATEN KLUNGKUNG",
    "Peran Penelitian 2": "Anggota",
    "Luaran Penelitian 2": "DOKUMEN RENCANA LAYANAN ANGKUTAN SISWA KAB. KLUNGKUNG",
    "Tahun Buku 1": "-",
    "Judul Buku 1": "-",
    "Penerbit Buku 1": "-",
    "Tahun Buku 2": "-",
    "Judul Buku 2": "-",
    "Penerbit Buku 2": "-",
    "Tahun Buku 3": "-",
    "Judul Buku 3": "-",
    "Penerbit Buku 3": "-",
    "Tahun Makalah 1": "-",
    "Judul Makalah 1": "-",
    "Penyelenggara Makalah 1": "-",
    "Tahun Makalah 2": "-",
    "Judul Makalah 2": "-",
    "Penyelenggara Makalah 2": "-",
    "Tahun Makalah 3": "-",
    "Judul Makalah 3": "-",
    "Penyelenggara Makalah 3": "-",
    "Tahun Konferensi 1": "2010",
    "Judul Konferensi 1": "SEMINAR NASIONAL PEMBANGUNAN BERKELANJUTAN YANG HEMAT DAN RAMAH LINGKUNGAN",
    "Penyelenggara Konferensi 1": "HIMPUNAN MAHASISWA TEKNIK SIPIL NON REGULER FT. UNUD",
    "Peran Konferensi 1": "Panitia",
    "Tahun Konferensi 2": "2013",
    "Judul Konferensi 2": "SEMILOKA PENGEMBANGAN PELABUHAN SANUR",
    "Penyelenggara Konferensi 2": "DINAS PERHUBUNGAN KOTA DENPASAR",
    "Peran Konferensi 2": "Peserta",
    "Tahun Konferensi 3": "2019",
    "Judul Konferensi 3": "FGD SISTEM ANGKUTAN TRANS METRO DEWATA",
    "Penyelenggara Konferensi 3": "DINAS PERHUBUNGAN KOTA DENPASAR",
    "Peran Konferensi 3": "Peserta",
    "Tahun Pengabdian 1": "-",
    "Nama Pengabdian 1": "-",
    "Tempat Pengabdian 1": "-",
    "Tahun Pengabdian 2": "-",
    "Nama Pengabdian 2": "-",
    "Tempat Pengabdian 2": "-",
    "Tahun Penghargaan 1": "-",
    "Bentuk Penghargaan 1": "-",
    "Pemberi Penghargaan 1": "-",
    "Tahun Penghargaan 2": "-",
    "Bentuk Penghargaan 2": "-",
    "Pemberi Penghargaan 2": "-",
    "Tahun Penghargaan 3": "-",
    "Bentuk Penghargaan 3": "-",
    "Pemberi Penghargaan 3": "-",
    "Tahun Organisasi 1": "2018",
    "Nama Organisasi 1": "IKATAN AHLI ANDALALIN  INDONENESIA",
    "Jabatan Organisasi 1": "ANGGOTA",
    "Tahun Organisasi 2": "-",
    "Nama Organisasi 2": "-",
    "Jabatan Organisasi 2": "-",
    "Program Studi": "Teknologi Rekayasa Transportasi",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.18/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  },
  {
    "Nama_Besar": "Ni Putu Happy Valentina Sugiyanti, M.Kom",
    "Nama": "Ni Putu Happy Valentina Sugiyanti, M.Kom",
    "Nama lengkap beserta gelar": "Ni Putu Happy Valentina Sugiyanti, S.Kom., M.Kom.",
    "NIP/NIK": "5106025402970004",
    "Tempat Lahir": "Siladan",
    "Tanggal Lahir": "14 Februari 1997",
    "TTL": "Siladan, 14 Februari 1997",
    "Jenis Kelamin": "Perempuan",
    "Status Perkawinan": "Kawin",
    "Agama": "Hindu",
    "Perguruan Tinggi": "Politeknik Digital Bali",
    "Alamat Perguruan Tinggi": "Jl. Bypass Ngurah Rai No.176, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali",
    "Facs Perguruan Tinggi": "0361-270128",
    "Alamat Rumah": "Dusun Peken Banjar Pempatan Banjarangkan Klungkung",
    "Facs Rumah": "082235302418",
    "E-Mail": "putuhappy97@gmail.com",
    "Tahun Lulus 1": "2018",
    "Perguruan Tinggi 1": "STMIK Primakara",
    "Prodi 1": "Sistem Informasi Akuntansi",
    "Tahun Lulus 2": "2024",
    "Perguruan Tinggi 2": "Universitas Pendidikan Ganesha",
    "Prodi 2": "Ilmu Komputer",
    "Tahun Lulus 3": "",
    "Perguruan Tinggi 3": "",
    "Prodi 3": "",
    "Tahun Pelatihan 1": "2019",
    "Jenis Pelatihan 1": "Dalam Negeri",
    "Penyelenggara Pelatihan 1": "Certification Official Seal Of Microsoft",
    "Jenis Sertifikat 1": "Pelatihan Microsoft Office",
    "Jangka Waktu Pelatihan 1": "3 hari",
    "Tahun Pelatihan 2": "",
    "Jenis Pelatihan 2": "",
    "Penyelenggara Pelatihan 2": "",
    "Jenis Sertifikat 2": "",
    "Jangka Waktu Pelatihan 2": "",
    "Tahun Kerja 1": "2020",
    "Jabatan Kerja 1": "Asisten Pengelola Aplikasi",
    "Tempat Bekerja 1": "Kantor Pertanahan Kabupaten Klungkung",
    "Tahun Kerja 2": "",
    "Jabatan Kerja 2": "",
    "Tempat Bekerja 2": "",
    "Tahun Kerja 3": "",
    "Jabatan Kerja 3": "",
    "Tempat Bekerja 3": "",
    "Tahun Penelitian 1": "2019",
    "Judul Penelitian 1": "Rancang   Bangun   Sistem   Informasi   Penjualan   dan   Penerimaan   Kas Berbasis Web Pada CV Bali Shanti ",
    "Peran Penelitian 1": "Ketua",
    "Luaran Penelitian 1": "Jurnal dan Skripsi",
    "Tahun Penelitian 2": "",
    "Judul Penelitian 2": "",
    "Peran Penelitian 2": "",
    "Luaran Penelitian 2": "",
    "Tahun Buku 1": "2019",
    "Judul Buku 1": "Rancang   Bangun   Sistem   Informasi   Penjualan   dan   Penerimaan   Kas Berbasis Web Pada CV Bali Shanti ",
    "Penerbit Buku 1": "Processor: Jurnal Ilmiah Sistem Informasi, Teknologi Informasi dan Sistem Komputer",
    "Tahun Buku 2": "2024",
    "Judul Buku 2": "Perencanaan Strategis Sistem Informasi Menggunakan Metode Ward and Peppard pada Kantor Pertanahan Kabupaten Klungkung ",
    "Penerbit Buku 2": "Jurnal Teknologi Sistem Informasi dan Aplikasi ",
    "Tahun Buku 3": "",
    "Judul Buku 3": "",
    "Penerbit Buku 3": "",
    "Tahun Makalah 1": "",
    "Judul Makalah 1": "",
    "Penyelenggara Makalah 1": "",
    "Tahun Makalah 2": "",
    "Judul Makalah 2": "",
    "Penyelenggara Makalah 2": "",
    "Tahun Makalah 3": "",
    "Judul Makalah 3": "",
    "Penyelenggara Makalah 3": "",
    "Tahun Konferensi 1": "2016",
    "Judul Konferensi 1": "Program Hibah Bina Desa",
    "Penyelenggara Konferensi 1": "Kemenristekdikti",
    "Peran Konferensi 1": "Peserta",
    "Tahun Konferensi 2": "",
    "Judul Konferensi 2": "",
    "Penyelenggara Konferensi 2": "",
    "Peran Konferensi 2": "",
    "Tahun Konferensi 3": "",
    "Judul Konferensi 3": "",
    "Penyelenggara Konferensi 3": "",
    "Peran Konferensi 3": "",
    "Tahun Pengabdian 1": "2016",
    "Nama Pengabdian 1": "Program Hibah Bina Desa",
    "Tempat Pengabdian 1": "Desa Songan Kintamani",
    "Tahun Pengabdian 2": "",
    "Nama Pengabdian 2": "",
    "Tempat Pengabdian 2": "",
    "Tahun Penghargaan 1": "2016",
    "Bentuk Penghargaan 1": "Sertifikat",
    "Pemberi Penghargaan 1": "LLDIKTI Wilayah VIII",
    "Tahun Penghargaan 2": "",
    "Bentuk Penghargaan 2": "",
    "Pemberi Penghargaan 2": "",
    "Tahun Penghargaan 3": "",
    "Bentuk Penghargaan 3": "",
    "Pemberi Penghargaan 3": "",
    "Tahun Organisasi 1": "",
    "Nama Organisasi 1": "",
    "Jabatan Organisasi 1": "",
    "Tahun Organisasi 2": "",
    "Nama Organisasi 2": "",
    "Jabatan Organisasi 2": "",
    "Program Studi": "Kecerdasan Buatan dan Robotik",
    "Hari penulisan surat": "Selasa",
    "Tanggal": "19",
    "Bulan": "November",
    "Status": "Tetap",
    "Status Caps": "TETAP",
    "Nomor SK": "NOMOR: SK.19/Y-BTW/XI/2024",
    "Jabatan": "Asisten Ahli"
  }
]

# Generate dokumen untuk setiap dosen dalam data_dosen_list
for i, data_dosen in enumerate(data_dosen_list):
    generate_cv(data_dosen, template_path, base_output_path)